
version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ndis
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  backend:
    build: ./backend
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
